### ISSUE TITLE
動かしてみたところ以下のエラーが出ました。何か解決策ありませんでしょうか？

### ISSUE THREAD

**Issue by fuchigam1** [YusukeHirao/MarkdownEditor#1]
masterに入っているものをそのまま clone してインストールしてみたところ、
以下の内容でエラーが出てしまいました。。

```
エラー: syntax error, unexpected '^', expecting ']'
File: /app/Plugin/MarkdownEditor/webroot/js/admin/markdown_editor/main.js
Line: 85
```

何か解決策ありませんでしょうか？

**Comment by YusukeHirao** [comment]
@materializing :+1: 

報告ありがとうございます。

う〜ん、正規表現の中の `<?` がPHPとして実行されていたりしますか？

実はまだローカルのPHP5.5しか試してないのですが、PHP5.4以上だとデフォルトでPHPのショートタグが有効なのでパースエラーになるんですよね。ショートタグはOFFにしてました。

あと、そもそもなぜ拡張子がjsのファイルがPHPのパースの影響を受けるのか理解できていないです。baserCMSって拡張子関係なしにPHPで実行されるんでしょうか?

**Comment by fuchigam1** [comment]
ショートタグOFFで届けたエラーは消えましたが、今度は
■ main.js:18576

```
Uncaught Error: Invariant Violation: _registerComponent(...): Target container is not a DOM element.
```

と出ちゃいました。環境は PHP 5.4.19 です。

PHPで実行はされないと思いますが、MarkdownEditorHelper での main.js の書き方の場合、ファイルの読込時にphpは経由します。

**Comment by YusukeHirao** [comment]
いろいろ調査が必要ですね。

時間がとれればこちらでやりとりしましょう。
[![Join the chat at https://gitter.im/YusukeHirao/MarkdownEditor](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/YusukeHirao/MarkdownEditor?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
